### ISSUE TITLE
Undeclared identifier: 'UIntPtr'

### ISSUE THREAD

**Issue by justinwaddy** [JackTrapper/bcrypt-for-delphi#2]
Hi there,

I have recently attempted to implement Jacktrapper's bcrypt-for-delphi. I am running Delphi 2010 and am receiving the error: [DCC Error] Bcrypt.pas(489): E2003 Undeclared identifier: 'UIntPtr'.

I read an article or two stating that Delphi often misidentifies UIntPtr for some or other reason. I am desperately needing help as I am implementing this into a school project which is due rather soon. Any help would be appreciated.

Thank you,
Justin

**Comment by JackTrapper** [comment]
The issue is that i have no idea what Delphi 2010 supports.

- **UnicodeString**

    - Added in Delphi 2009
    - Use `{$IFDEF UNICODE}`

- **TBytes**

    - **Delphi 5:** Doesn't exist. Declare our own `TBytes = array of Byte;`
    - **Delphi 7**: Has `Types.TByteDynArray`. Declare an alias `TBytes = Types.TByteDynArray;`
    - **Delphi 2010:** ?
    - **Delphi XE:** ?
    - **Delphi XE2:** ?
    - **Delphi XE6:** Has `SysUtils.TBytes`

- **UIntPtr**

    - **Delphi 5:** Doesn't exist. Declare our own `UIntPtr = Cardinal;`
    - **Delphi 7:** Doesn't exist. Declare our own `UIntPtr = Cardinal;`
    - **Delphi 2010:** ?
    - **Delphi XE:** ?
    - **Delphi XE2:** ?
    - **Delphi XE6:** Has `SysUtils.UIntPtr`

With **UIntPtr** and took a guess that it was added after Delphi 7. Now it seems it wasn't added until *sometime* after Delphi 2010? Changed the code to assume that **UIntPtr** came into existence after Delphi 2010:

- **UIntPtr**

    - **Delphi 5:** Doesn't exist. Declare our own `UIntPtr = Cardinal;`
    - **Delphi 7:** Doesn't exist. Declare our own `UIntPtr = Cardinal;`
    - **Delphi 2010:** ~~?~~ Didn't exist. Declare our own `UIntPtr = Cardinal;`
    - **Delphi XE:** ?
    - **Delphi XE2:** ?
    - **Delphi XE6:** Has `SysUtils.UIntPtr`

That may resolve the **UIntPtr**; but i still don't know when **TBytes** came into existence.

**Comment by justinwaddy** [comment]
So in terms of alterations to the current code, what should I change, as
the code does contain a line 'uIntPtr = Cardinal'. Thank you for your swift
reply by the way, and I appreciate you responding on a Sunday.

**Comment by JackTrapper** [comment]
Dammit; i forgot to hit Sync 2 hours ago.

Yes, hopefully if i got the compiler conditional defines correct, then the line:

    {$IFNDEF COMPILER_15_UP}
    	//Someone said that Delphi 2010 (Delphi 14) didn't have UIntPtr.
    	//So maybe it was Delphi XE (Delphi 15)
    	UIntPtr = Cardinal; //an unsigned, pointer sized, integer
    {$ENDIF}

will be seen by the compiler. If not, you can force it to be seen by removing the *conditional defines* around it:

    {IFNDEF COMPILER_15_UP}
    	//Someone said that Delphi 2010 (Delphi 14) didn't have UIntPtr.
    	//So maybe it was Delphi XE (Delphi 15)
    	UIntPtr = Cardinal; //an unsigned, pointer sized, integer
    {ENDIF}

**Comment by justinwaddy** [comment]
Thank you so much - I'll test it as soon as I get home, & thank you for
responding so quickly. Quite a beautiful implementation by the way - let me
know if you ever need a favour in Cape Town.

**Comment by justintopiary** [comment]
Woohoo! It works - I simply commented out the two conditions and it now
functions as normal.

**Comment by justinwaddy** [comment]
![delphi 2010 bcrypt fix](https://user-images.githubusercontent.com/41863934/43369564-168933b6-9371-11e8-84b4-066910c7a2da.png)

I simply needed to comment out the two lines pictured above and it now works perfectly on Delphi 2010. Thanks for your help, JackTrapper.

[At lines 191-193 insert the below '//'s ]
//{$IFDEF COMPILER_7_DOWN}
	UIntPtr = Cardinal;
//{$ENDIF}

**Comment by JackTrapper** [comment]
I'm still curious if my latest commit also fixes it; so that the define can be left in.
