### ISSUE TITLE
Add EnhancedHashPassword?

### ISSUE THREAD

**Issue by 13thbit** [JackTrapper/bcrypt-for-delphi#3]
The following comment on stackexchange by Ian Boyd refers to DropBox _pre-hashing_ passwords to circumvent the 71 byte password length limitation. It would be great if this also was implemented in the Delphi version of BCrypt
 
https://security.stackexchange.com/a/184090

Thanks for the current and future implementations!

**Comment by JackTrapper** [comment]
Done.
