### ISSUE TITLE
LongWord  stored a 64 bit ?

### ISSUE THREAD

**Issue by Zeus64** [JackTrapper/bcrypt-for-delphi#6]
In the code you write :

- Idera redefined the "fundamental" LongWord type to no longer be 32-bits. It is now 32-bits on 16-bit platforms, 32-bits on 32-bit platforms, and 64-bits on 64-bit platforms. And Cardinal, the "generic" type, as been changed to be 16-bits on 16-bit platforms, 32-bits on 32-bit platforms, and 32-bits on 64-bit platforms. This means they violated the contract of correctly written code - retroactively breaking all existing code.

but that not true ? where did you see that ?

**Comment by JackTrapper** [comment]
> but that not true ? where did you see that ?

The Delphi [documentation](http://docwiki.embarcadero.com/RADStudio/XE8/en/What%27s_New_in_Delphi_and_C%2B%2BBuilder_XE8#Changes_in_LongInt_and_LongWord_Size_for_64-bit_iOS_Platforms)

> **Changes in LongInt and LongWord Size for 64-bit iOS Platforms**
> 
> LongInt and LongWord are now platform-dependent integer types.
> 
> On 64-bit iOS platforms, LongInt and LongWord are double the size that is supported on 32-bit platforms

So if you have code that assumed that **LongInt** and **LongWord** were *"Fundamental types"*, that assumption is no longer true.

```
| Type        | 16-bit platform | 32-bit platform | 64-bit platform  |
|-------------|-----------------|---------------- |------------------|
| Integer     | 16-bit signed   |            32-bit signed           | "generic type"
| Cardinal    | 16-bit unsigned |            32-bit unsigned         | "generic type"

| Longint     | 32-bit signed   | 32-bit signed   | 64-bit signed    | "fundamental type"
| Longword    | n/a             | 32-bit unsigned | 64-bit unsigned  | "fundamental type"
| Int64       | n/a             | 64-bit signed   | 64-bit signed    | "fundamental type"
| UInt64      | n/a             | 64-bit unsigned | 64-bit unsigned  | "fundamental type"
| Int32       | n/a             |            32-bit signed           |  
| UInt32      | n/a             |            32-bit unsigned         | 

| NativeInt   | n/a             | 32-bit signed   | 64-bit signed    |
| NativeUInt  | n/a             | 32-bit unsigned | 64-bit unsigned  |

| FixedInt    | n/a             |            32-bit signed           |
| FixedUInt   | n/a             |            32-bit unsigned         |
```

BCrypt was written to the Delphi language standard, which made certain promises. 

Those promises were broken; hence the need to change.
